#!/bin/bash
# List of environment variables and module loads for open-instruct tasks

# CUDA version - adjust based on ABCI available versions
# ABCI available: cuda/12.8/12.8.1
export OPEN_INSTRUCT_CUDA_VERSION_MAJOR=12
export OPEN_INSTRUCT_CUDA_VERSION_MINOR=8
export OPEN_INSTRUCT_CUDA_VERSION_PATCH=1  # Changed from 0 to 1

export OPEN_INSTRUCT_CUDA_VERSION=${OPEN_INSTRUCT_CUDA_VERSION_MAJOR}.${OPEN_INSTRUCT_CUDA_VERSION_MINOR}
export OPEN_INSTRUCT_CUDA_VERSION_SHORT=${OPEN_INSTRUCT_CUDA_VERSION_MAJOR}${OPEN_INSTRUCT_CUDA_VERSION_MINOR}
export OPEN_INSTRUCT_CUDNN_VERSION=9.5
export OPEN_INSTRUCT_CUDNN_VERSION_WITH_PATCH=9.5.1
export OPEN_INSTRUCT_HPCX_VERSION=2.20
export OPEN_INSTRUCT_NCCL_VERSION=2.23
export OPEN_INSTRUCT_NCCL_VERSION_WITH_PATCH=2.23.4-1

# Python and PyTorch versions
export OPEN_INSTRUCT_PYTHON_VERSION=3.12.8
export OPEN_INSTRUCT_TORCH_VERSION=2.8.0
export OPEN_INSTRUCT_FLASH_ATTENTION_VERSION=2.8.3

# Load modules
source /etc/profile.d/modules.sh
module load cuda/${OPEN_INSTRUCT_CUDA_VERSION}/${OPEN_INSTRUCT_CUDA_VERSION}.${OPEN_INSTRUCT_CUDA_VERSION_PATCH}
module load cudnn/${OPEN_INSTRUCT_CUDNN_VERSION}/${OPEN_INSTRUCT_CUDNN_VERSION_WITH_PATCH}
module load hpcx/${OPEN_INSTRUCT_HPCX_VERSION}
module load nccl/${OPEN_INSTRUCT_NCCL_VERSION}/${OPEN_INSTRUCT_NCCL_VERSION_WITH_PATCH}

export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
