#カテゴリー数は2または5の倍数にしないでください
category = [
  { "category": "中1", "unit": "一次方程式" },
  { "category": "中1", "unit": "文字式" },
  { "category": "中1", "unit": "正負の数" },
  { "category": "中1", "unit": "比例反比例" },
  { "category": "中2", "unit": "一次関数" },
  { "category": "中2", "unit": "文字式" },
  { "category": "中2", "unit": "確率" },
  { "category": "中2", "unit": "連立方程式" },
  { "category": "中3", "unit": "二次方程式" },
  { "category": "中3", "unit": "二次関数" },
  { "category": "中3", "unit": "展開と因数分解" },
  { "category": "中3", "unit": "平方根" },
  { "category": "IA", "unit": "2次関数" },
  { "category": "IA", "unit": "場合の数と確率" },
  { "category": "IA", "unit": "数と式" },
  { "category": "IA", "unit": "整数の性質（数学と人間活動）" },
  { "category": "IIB", "unit": "いろいろな式" },
  { "category": "IIB", "unit": "三角関数" },
  { "category": "IIB", "unit": "微分法・積分法" },
  { "category": "IIB", "unit": "指数・対数" },
  { "category": "IIB", "unit": "数列" },
  { "category": "IIB", "unit": "統計的な推測" },
  { "category": "IIIC", "unit": "微分" },
  { "category": "IIIC", "unit": "極限" },
  { "category": "IIIC", "unit": "積分" },
  { "category": "IIIC", "unit": "ベクトル" },
  { "category": "IIIC", "unit": "平面上の曲線と複素数平面" }
]